import { Playpen_Sans, Pacifico, Lobster_Two, Merienda, Sofia } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const playpen = Playpen_Sans({ subsets: ["latin"], weight: ['400'] });
const pacifico = Pacifico({ subsets: ["latin"], weight: ['400'] });
const lobster = Lobster_Two({ subsets: ["latin"], weight: ['400'] });
const merienda = Merienda({ subsets: ["latin"], weight: ['400'] });
const sofia = Sofia({ subsets: ["latin"], weight: ['400'], variable: '--font-sofia' });



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={playpen.className}>
      <Image 
          src='/assets/esc.png'
          width={206}
          height={120}
          alt="line"
          className="ml-1 pt-0 pb-3 h-[104px] w-[190px]"
          />
        {children}
      </body>
    </html>
  );
}
