import { Nanum_Pen_Script } from "next/font/google";
import "./globals.css";

const inter = Nanum_Pen_Script({ subsets: ["latin"], weight: ['400'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
